# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    working_directory: /gbs
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
        # Creates a separate environment for each build for security.
        # This environment is remote, fully-isolated and has been configured to execute Docker commands.
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/gbs.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/gbs.tar | true
      - run:
          name: Build gbs Docker image
          command: |
            docker build --cache-from=gbs -t gbs .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/gbs.tar gbs
